### ISSUE TITLE
Begin app construction 

### ISSUE THREAD

**Issue by KareemGordon** [JavaTeamUp/MessageApp#5]
Create both the login page and the registration page for TeamUp app

- [x] Make sure all navigation bar buttons work
- [x] Be able to see navigation bar
- [x] Finalize colors for app

**Comment by eddiefootball2** [comment]
App colors : 
Main: Lavender 
Secondary: White
Tertiary: Dark Grey

**Comment by nysimpson** [comment]
- The  parse backend was setup
- Herkuo was setup
- Created a login form that works
- Created a registration form, but not connected
- Login and Registration forms styled
- Nav menu layout complete, but buttons not working

**Comment by nysimpson** [comment]
The navigation is now working. We have also decided not to include groups, but to only allow current users to add each other as friends.
